### PR TITLE
Update to PHP 8

### PR DESCRIPTION
**Pull request by SenseException**
This PR replaces #28 because of the need for using a newer Persistence version

### CODE REVIEW

**Comment by SenseException** [comment]
Persistence 2.* has at least one missing `class-string` type that causes some compatibility headache. I'll update to Persistence 3.* and proceed with the update steps. The few composer dependants out there don't look like that they're still maintained.

**Comment by SenseException** [comment]
Static analysis errors have risen from 6 to 30 errors. The other workflows are green. I guess I'm closer to a PR.

**Comment by SenseException** [comment]
@greg0ire or someone else: Could you please take a look at the ignoreErrors of phpstan.neon.dist? I'm not sure if these can be fixed without changing the whole skeleton-mapper because of differences between skeleton-mapper and Persistence.

**Comment by greg0ire** [comment]
Took a look, and it looks quite complicated. I think we should merge as is?

**Comment by SenseException** [comment]
I'll create a new Branch for a major release.

**Comment by SenseException** [comment]
Done.

The majority of this PR after the dependency updates are PHPStan fixes + fixes of ignoreErrors and Coding Standard adaptations and fixes of previously excluded rules.

**Review by greg0ire — APPROVED** [review]

**Comment by SenseException** [comment]
Thanks for the patience until this got finished. :white_flower:

**Comment by greg0ire** [comment]
Thanks for doing this :)

**Pull request merged**
