### PR TITLE
Add PHPUnit to require-dev, remove composer.lock

### PR DESCRIPTION
**Pull request by billschaller**

### CODE REVIEW

**Comment by jwage** [comment]
What is the failure?

**Comment by zeroedin-bill** [comment]
Uh... you need phpunit to run the tests?

**Comment by ovr** [comment]
:+1:

**Comment by billschaller** [comment]
Wat

**Comment by jwage** [comment]
Sorry my comment didn't make it. This was changed in another commit fc8c9f3b23f9275929b3d01ec1f099d9af19036a. But now tests in travis seem to be failing but I haven't had a chance to look yet.

**Pull request closed without merging**
